config/routes.rb
SniffSound::Application.routes.draw do

  get "comments/create"

  get "comments/destroy"

  get "comment/create"

  get "comment/destroy"

  get "fan_band_relationships/create"

  get "fan_band_relationships/destroy"

  root to: 'pages#home'
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/home', to: 'pages#home'
  match '/about', to: 'pages#about'
  match '/dashboard', to: 'pages#dashboard'
  match '/explore', to: 'pages#explore'
  match '/profile', to: 'pages#profile'
  match '/search', to: 'pages#search'
  
  match '/users/search_autocompletion', to: 'users#search_autocompletion'
  
  match '/auth/:provider/callback', to: 'users#new'
  match '/auth/failure', to: 'users#failure'
  
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy] #routes per il controller di sessione (specifico quali devono essere i metodi accessibili dal controller)
  resources :bands
  resources :events do
    collection do
      get :search
    end
  end

  resources :user_event_relationships
  resources :fan_band_relationships, only:[:create, :destroy]
  resources :comments, only:[:create, :destroy]
  resources :user_user_relationships, only:[:create, :destroy]
  
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :content, :event_id, :user_id
  validates_presence_of [:user_id, :event_id, :content]
  validates :content, length: {minimum:1, maximum:140}
  
  belongs_to :event
  belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :signed_in_user
  
  def create
    @event = Event.find_by_id(Integer(params[:event_id]))
    if @event.comment(params[:content],current_user.id)
      @comment = @event.comments.where(user_id:current_user.id).order('created_at DESC').first
      respond_to do |format|
        format.html {redirect_to request.referer}
        format.js
      end
    end
  end

  def destroy
    @comment = Comment.find_by_id(params[:id])
    @event = Event.find_by_id(@comment.event_id)
    if @comment.destroy
      respond_to do |format|
        format.html {redirect_to request.referer}
        format.js
      end
    end
  end
end

app/views/comments/_comment.html.erb
<% style=""
	if not @visibility
		style='style=display:none'
	end%>
<article class="well event_comment" id="commento<%= comment.id %>" <%= style %>>
	
	<div class="row">
		<div class="span1">
			<% @user = comment.user %>
			<%= render 'users/profile_pic_logged', user:@user%>
		</div>
		<div class="span6">
			<span><b><%= link_to @user.fullname, user_path(@user) %></b></span>
			<p><%= comment.content %></p> 
			<p> del <%= comment.created_at.strftime('%d/%m/%Y') %>,  alle  <%= comment.created_at.strftime('%H:%M') %> </p>
		</div>
		<a href="#" class="preferito"><i class="icon-star"></i></a>
	</div>
</article>

app/views/comments/_comment_submit.html.erb
<%= form_tag('/comments', method: :post, remote: true) do %>
	<%= text_field_tag 'content', nil, placeholder: 'Scrivi qui il tuo commento!'%>
	<%= hidden_field_tag 'event_id', @event.id %>
	<%= submit_tag 'Commenta!' %>
<% end %>

app/views/comments/_comment_user.html.erb
<!-- TODO: i commenti possono avere un "like" ? io per adesso ho messo la stella in altro a destra ma non fa niente -->

<article class="user_comment_recent well">
	<div class="row">
		<div class="span1">
			<% @user = comment_user.user %>
			<% @event = comment_user.event %>
			<%= render 'users/profile_pic_logged', user:@user%>
		</div>
		<div class="span6">
			<span><b><%= link_to @event.name, event_path(@event) %></b></span>
			<p><%= comment_user.content %></p> 
			<p> del <%= comment_user.created_at.strftime('%d/%m/%Y') %>,  alle  <%= comment_user.created_at.strftime('%H:%M') %> </p>
		</div>
		<a href="#" class="preferito"><i class="icon-star"></i></a>
	</div>
</article>

app/views/comments/_comments.html.erb
<section class="streamline">
	<h3>Streamline</h3>
	<div id="comment_submit_event<%= @event.id %>" class="submit">
		<%= render 'comments/comment_submit', event:@event %>
	</div>
	<div id="comment_list_event<%= @event.id %>" class="well comment_list">
		<% @comments = @event.comments.order('created_at DESC')
		if not @comments.empty? 
			@visibility = true
		%>
			<%= render partial: 'comments/comment', collection:@comments, event:@event, visibility:@visibility %>
		<% end %>
	</div>
</section>

app/views/comments/create.js.erb
$("#comment_submit_event<%= @event.id %> form")[0].reset();
$("#comment_list_event<%= @event.id %>").prepend('<%= escape_javascript(render('comments/comment', comment: @comment, visibility: @visibility)) %>');
$("#comment_list_event<%= @event.id %> #commento<%= @comment.id %>").slideDown('medium', null);

app/views/comments/destroy.js.erb
$("#comment_list_event<%= @event.id %> #commento<%= @comment.id %>").slideUp('medium', function(){
	$("#comment_list_event<%= @event.id %> #commento<%= @comment.id %>").remove();
});