config/routes.rb
SniffSound::Application.routes.draw do

  get "comments/create"

  get "comments/destroy"

  get "comment/create"

  get "comment/destroy"

  get "fan_band_relationships/create"

  get "fan_band_relationships/destroy"

  root to: 'pages#home'
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/home', to: 'pages#home'
  match '/about', to: 'pages#about'
  match '/dashboard', to: 'pages#dashboard'
  match '/explore', to: 'pages#explore'
  match '/profile', to: 'pages#profile'
  match '/search', to: 'pages#search'
  
  match '/users/search_autocompletion', to: 'users#search_autocompletion'
  
  match '/auth/:provider/callback', to: 'users#new'
  match '/auth/failure', to: 'users#failure'
  
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy] #routes per il controller di sessione (specifico quali devono essere i metodi accessibili dal controller)
  resources :bands
  resources :events do
    collection do
      get :search
    end
  end

  resources :user_event_relationships
  resources :fan_band_relationships, only:[:create, :destroy]
  resources :comments, only:[:create, :destroy]
  resources :user_user_relationships, only:[:create, :destroy]
  
  

end

app/models/user.rb
class User < ActiveRecord::Base
  include ActiveModel::UserValidators
  attr_accessible :email, :fullname, :password, :password_confirmation, :twitter_uid, 
                  :facebook_uid, :birthdate, :city, :profilepic, :avatar_remote_url, :remember_me, :updating_password
  
  @check_password = true

  has_attached_file :profilepic, styles:{medium:"300x300#",thumb:"100x100#"}, :default_url=>"/system/events/posters/missing/thumb.png"
  
  has_many :events, dependent: :destroy
  has_many :user_event_relationships, dependent: :destroy
  has_many :participating_events, through: :user_event_relationships, source: :event
  has_many :user_genre_relationships, dependent: :destroy
  has_many :genres, through: :user_genre_relationships, source: :genre
  has_many :favourite_genres, through: :user_genre_relationships, source: :genre
  
  has_many :user_band_relationships, dependent: :destroy
  has_many :bands, through: :user_band_relationships, source: :band
  
  has_many :user_user_relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :user_user_relationships, source: :followed
  has_many :user_reverse_relationships, foreign_key: :followed_id, 
                                   class_name: "UserUserRelationship",
                                   dependent: :destroy
  has_many :followers, through: :user_reverse_relationships, source: :follower
  
  
  has_many :fan_band_relationships, dependent: :destroy
  has_many :favourite_bands, through: :fan_band_relationships, source: :band
  
  has_many :comments, dependent: :destroy
  
  has_secure_password
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  before_save { |user| user.email = email.downcase } #forza la scrittura della mail prima del rollback, e controlla che non ci sia già
  before_save :create_remember_token
  
  #metodi per validare i campi dell'utente
  validates :email, presence: true,
                    format: {with: VALID_EMAIL_REGEX},
                    uniqueness: { case_sensitive: false,
                                   message: "email in uso" }
  validates :fullname, presence: true,
                      length: {minimum: 5, maximum: 30}
  validates :password, length: { minimum: 6 },
                      presence: { on: :create }, if: :should_validate_password?
  validates :password_confirmation, presence: true, if: :should_validate_password?
  validates :birthdate, presence:true, birth_date:true

#---------------------------------------metodi per i fan delle band---------------------------------------------------------------------
def fan!(band)
  self.fan_band_relationships.create(band_id:band.id)
end

def unfan!(id)
  self.fan_band_relationships.find_by_id(Integer(id)).destroy
end 

def fan?(band)
  !self.fan_band_relationships.find_by_band_id(band.id).nil?
end
 
#---------------------------------------metodi per le relazioni di partecipazione-----------------------------------------------------------  
  def participating?(event)
    user_event_relationships.find_by_event_id(event.id)
  end
  
  def participate!(event)
    user_event_relationships.create!(event_id: event.id)
  end
  
  def unparticipate!(event)
    user_event_relationships.find_by_event_id(event.id).destroy
  end
  
#--------------------------------------------metodi per le relazioni tra gli utenti-----------------------------------------------------------

  def following?(other_user)
    user_user_relationships.find_by_followed_id(other_user.id)
  end

  def follow!(other_user)
    user_user_relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(id)
    user_user_relationships.find_by_id(Integer(id)).destroy
  end


  
#-----------------------------------metodi per la ricerca degli utenti----------------------------------------------------------------------    
  def self.search(params)
    if params
      where('fullname ILIKE ?',  "%#{params[:search]}%") #ILIKE per il case sensitive = false
     else
       scoped
     end  
   end   
   
#-----------------------------------metodi per la relazione di generi preferiti
def saveFavouriteGenres(params)
  if not params.nil?
    params.each do |k,i|
      self.user_genre_relationships.create(genre_id: Genre.find(k).id)
    end
  end
end

#-----------------------------------Per aggiornare il profilo
def update_attributes_and_genres(params)
  @check_password = false
  if not self.user_genre_relationships.nil? 
    self.user_genre_relationships.each do |ob|
      ob.destroy
    end
  end
  self.saveFavouriteGenres(params[:genre])
  self.update_attributes(params[:user])
end

def should_validate_password? #per evitare che richieda la presenza della password quando aggiorno il profilo
  @check_password && true
end

#-----------------------------------metodo per creare il rember_token usato per la sessione utente----------------------------------
 
def create_remember_token
  self.remember_token = SecureRandom.base64 #metodo per la cifratura del token
end 
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  require 'date'
  before_filter :signed_in_user, only: [:edit, :update, :index]
  before_filter :correct_user, only: [:edit, :update] #l'utente può modificare solo la sua pagine
  
  
  def new
    @title = "Sign up"
    
    auth_hash = request.env["omniauth.auth"]
    if auth_hash.nil?
      redirect_url = '/auth/'+params['p'];
      redirect_to redirect_url
      
    #TWITTER---------------------------------------------------------------------------------------------------------------------------------------  
    elsif params['provider']=='twitter'
      city = city_splitting(auth_hash)
      
      @avatar = auth_hash['info']['image']
      @user = User.new(twitter_uid:auth_hash['uid'], 
                       fullname:auth_hash['info']['name'],
                       city:city,
                       avatar_remote_url:auth_hash['info']['image'])
                 
    #FACEBOOK----------------------------------------------------------------------------------------------------------------------------------------      
    elsif params['provider']=='facebook'
      city = city_splitting(auth_hash)
      birthdate = birthday_parsing(auth_hash)
       
      @avatar = auth_hash['info']['image']
      @user = User.new(facebook_uid:auth_hash['credentials']['token'], 
                       fullname:auth_hash['info']['name'],
                       email:auth_hash['info']['email'],
                       city:city,
                       birthdate:birthdate,
                       avatar_remote_url:auth_hash['info']['image'])
    end
  end
  
  def show
    @user = User.find(params[:id])
    @events = @user.events
    @number_events_created = @events.length #numero eventi creati dall'utente
    @participating_events = Event.search_events_participating(@user) #eventi a cui l'utente parteciperà
    @participated_events = Event.search_events_participated(@user) #eventi a cui l'utente ha partecipato
    @events_most_popular = Event.search_most_popular #restituisce i primi 10 eventi più partecipati in totale
    @events_most_popoluar_followed_users = #
    @comments = @user.comments
    @last_comments = @user.comments.order('created_at DESC').limit(3)
    
    
    @followed_users = @user.followed_users.paginate(page: params[:page])
    @followers = @user.followers.paginate(page: params[:page])

  end
  
  #ottengo tutti gli utenti. mi serve nel search
  def index
      @users = User.paginate(page: params[:page])
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      if not params[:genre].nil?
        @user.saveFavouriteGenres(params[:genre])
      end
      sign_in_without_permanent_cookies @user #la prima volta salva il cookie solo per la sessione
      flash[:success] = "Benvenuto in SniffSound!"
      #UserMailer.registration_confirmation(@user).deliver
      redirect_to root_path #torno alla home, che (visto che ora l'utente è loggato) reidirizzerà alla dashboard
    else
      render 'new' #ritorna al new con messaggi d'errore
    end
  end
  
  def failure
    redirect_to root_url, :alert => "Authentication error: #{params[:message].humanize}"
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
     @user = User.find(params[:id])
    if @user.update_attributes_and_genres(params)
      #faccio il salvataggio nel DB, con update_attributes che deve di nuovo passare tutti i validatori del modello
      flash[:success] = "Profilo aggiornato!"
      sign_in @user
      redirect_to root_path
    else
      render 'edit'  #ritorna all'edit per le modifiche
    end
  end
  
  
  def search_autocompletion
    @users = User.search(params)
    #@users = User.all
    respond_to do |format|
      format.html
      format.js
    end
  end
  
  
  
  
private  
# -----------------------------------------------METODI PRIVATI-------------------------------------------
  def correct_user #controllo id utente = current_user
    @user = User.find(params[:id])
    if !current_user?(@user) #controllo id utente = current_user
      redirect_to root_path
    end
  end
  
  def city_splitting(auth_hash) #gestione dello split della città 
    #gestione della città e dello split
     city = auth_hash['info']['location'] 
     if city
      city = city.split(', ')[0]
     end    
  end
  
  def birthday_parsing(auth_hash) #gestione della data di nascita
    birthdate = auth_hash['extra']['raw_info']['birthday']
      #render text: birthdate 
      if birthdate
        birthdate = Date.strptime(birthdate, '%m/%d/%Y') #hash-->Date object
      end
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_aside_user.html.erb
<div class="aside_user">
	<%= image_tag("user_default.png") %>
	<%= link_to current_user.fullname, url_for(current_user) %>
</div>

app/views/users/_controls.html.erb
<div id = "user_controls<%= @user.id %>" class="user_follow_controls<%= @user.id %>">
<% if !current_user?(@user)%>
	<% if signed_in? %>
			<% if not current_user.following?(@user) %>
				<%= render 'users/follow', user:@user %>
			<% else %>
				<%= render 'users/unfollow', user:@user %>
			<%end%>
		<% end %>
<% end %>
</div>

app/views/users/_follow.html.erb
<%= link_to "Segui", user_user_relationships_path(followed_id:@user.id, follower_id:current_user.id), id: "follow_#{@user.id}", class:"btn btn-small btn-success", remote: true, method: :post %>

app/views/users/_profile_pic.html.erb
<%	
	if not user.profilepic_file_name.nil?
		if(@size=="medium")
			address = user.profilepic.url(:medium)
		# elsif(@size=="small")
			# address = user.profilepic.url(:small)
		else
			address = user.profilepic.url(:thumb)
		end
	else
		if user.avatar_remote_url.nil?
			address = "user_default.png"
		else
			address = user.avatar_remote_url
		end
	end
%>
<%= image_tag address, class:'img_profilo' %>

app/views/users/_profile_pic_logged.html.erb
<%
	if not @user.profilepic_file_name.nil?
		if(@size=="medium")
			address = @user.profilepic.url(:medium)
		elsif(@size=="small")
			address = @user.profilepic.url(:small)
		else
			address = @user.profilepic.url(:thumb)
		end
		
		
	else
		if @user.avatar_remote_url.nil?
			address = "user_default.png"
		else
			address = @user.avatar_remote_url
		end
	end
	
%>

<%= image_tag address, class:'img_profilo', id: "logged_photo"  %>

app/views/users/_unfollow.html.erb
<% @relationship = current_user.user_user_relationships.find_by_followed_id(@user.id)%>
<%= link_to "Non seguire più", user_user_relationship_path(id:@relationship.id), remote: true, id: "follow_#{@user.id}", class:"btn btn-small btn-danger", method: :delete %>

app/views/users/edit.html.erb
<%= provide(:title, 'Edit User: '+@user.fullname) %>
<div class="row">
  <div class="span8 offset2">
  	
  	<h1 id="benvenuto">Modifica i tuoi dati</h1>
  	
  	<%= form_for(@user,html:{multipart:true}) do |f| %>
	  <%= render 'shared/error_messages', object: f.object %> <!-- visualizza i messaggi di errore -->
	  <ol>
	  	  <li>Come ti chiami e quando sei nato/a?</li><hr>
		  <%= f.text_field :fullname, placeholder: "Nome e Cognome" %>
	      <%= render 'shared/error_messages_for', object: f.object, field: :fullname %>
	      <%= f.date_select :birthdate, start_year: 1950, end_year: 2000, order: [:day, :month, :year]%>
	      <%= render 'shared/error_messages_for', object: f.object, field: :birthdate %>
	      
	      <li>Inserisci una tua foto</li><hr>
	      <%= render 'users/profile_pic', user:@user %>
	      <%= f.hidden_field :avatar_remote_url, value:@avatar %>
	      <%= f.file_field :profilepic %>
		  <%= render 'shared/error_messages_for', object: f.object, field: :profilepic %> 
		  <%= f.hidden_field "avatar_remote_url", value: @user.avatar_remote_url %>
	      
	      <li>Dove abiti?</li><hr>
		  <%= f.text_field :city, placeholder: "Città"  %>
	      <%= render 'shared/error_messages_for', object: f.object, field: :city %>
	      
	      <li>Quali generi musicali preferisci?</li><hr>
	      <% Genre.all.each do |genre| %>
	      	<div class="checkbox_container">
	      		<%= label_tag "genre[#{genre.id}]", genre.name %>
	      		<% if @user.genres.find_by_id(genre.id).nil? %>
	      			<%= check_box_tag "genre[#{genre.id}]" %>
	      		<% else %>
	      			<%= check_box_tag "genre[#{genre.id}]", nil, checked:true %>
	      		<% end %>
	      	</div>
	      <% end %>

		  <li>Le tue credenziali di accesso</li><hr>
	      <%= f.text_field :email, placeholder: "Email" %>
	      <%= render 'shared/error_messages_for', object: f.object, field: :email %>
	      
	      
	      
	  </ol>
	  
      <%= f.hidden_field :twitter_uid %>
      <%= f.hidden_field :facebook_uid %>


      <%= f.submit "Salva le modifiche", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
  <script type="text/javascript">
  	$('.edit_user').submit(function() {
		if ($(this).valid())
			$("input[type='submit']").button("loading");
		return true;
	});
  </script>
</div>

app/views/users/new.html.erb
<%= provide(:title, 'Sign up') %>

<div class="row">
  <div class="span8 offset2">
  	
  	<h1 id="benvenuto">Benvenuto! Completa il tuo profilo</h1>
	
    <%= form_for(@user,html:{multipart:true}) do |f| %>
	  <%= render 'shared/error_messages', object: f.object %> <!-- visualizza i messaggi di errore -->
	  <ol>
	  	  <li>Come ti chiami e quando sei nato/a?</li><hr>
		  <%= f.text_field :fullname, placeholder: "Nome e Cognome" %>
	      <%= render 'shared/error_messages_for', object: f.object, field: :fullname %>
	      <%= f.date_select :birthdate, start_year: 1950, end_year: 2000, order: [:day, :month, :year]%>
	      <%= render 'shared/error_messages_for', object: f.object, field: :birthdate %>
	      
	      <li>Inserisci una tua foto</li><hr>
	      <%= image_tag @avatar, class: '#'%>
	      <%= f.hidden_field :avatar_remote_url, value:@avatar %>
	      <%= f.file_field :profilepic %>
		  <%= render 'shared/error_messages_for', object: f.object, field: :profilepic %> 
		  <%= f.hidden_field "avatar_remote_url", value: @user.avatar_remote_url %>
	      
	      <li>Dove abiti?</li><hr>
		  <%= f.text_field :city, placeholder: "Città"  %>
	      <%= render 'shared/error_messages_for', object: f.object, field: :city %>
	      
	      <li>Quali generi musicali preferisci?</li><hr>
	      <% Genre.all.each do |genre| %>
	      	<div class="checkbox_container">
	      		<%= check_box_tag "genre[#{genre.id}]" %>
	      		<%= label_tag "genre[#{genre.id}]", genre.name %>
	      	</div>
	      <% end %>

		  <li>Le tue credenziali di accesso</li><hr>
	      <%= f.text_field :email, placeholder: "Email" %>
	      <%= render 'shared/error_messages_for', object: f.object, field: :email %>
	      <%= f.password_field :password, placeholder: "Password" %>
	      <%= render 'shared/error_messages_for', object: f.object, field: :password %>
	      <%= f.password_field :password_confirmation, placeholder: "Conferma" %>
	      <%= render 'shared/error_messages_for', object: f.object, field: :password_confirmation %>
	      
	      
	      
	  </ol>
	  

      <%= f.hidden_field :twitter_uid %>
      <%= f.hidden_field :facebook_uid %>


      <%= f.submit "Entra in SniffSound!", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
  <script type="text/javascript">
  	$('#new_user').submit(function() {
		if ($(this).valid())
			$("input[type='submit']").button("loading");
		return true;
	});
  </script>
</div>

app/views/users/search_autocompletion.js.erb
var users_autocompletion = <%= @users.to_json.html_safe %>;

app/views/users/show.html.erb
<%= provide(:title, @user.fullname) %>
<% @user_copy = @user %>

<%
# TODO: immagine per le band da mettere nell'aside ?
# TODO: link per i "tutti..." in un div modale ?
# TODO: comportamento dinamico quando partecipo o non partecipo più ad un evento! (es: scompare/appare, cambiano i contatori..)
%>

<%= javascript_include_tag "page-specific/regola_altezza_aside" %>

<div class="row">
	
	<div class="span7 offset1">
		<!--contenuto informazioni utente-->
		<div class="row hidden-phone" id="row_profilo">
			<div class="span2" id="foto_profilo">
				<%= render 'users/profile_pic_logged', user: @user, size: "medium"%>
			</div>
			<div class="span5" id="descr_profilo">
					<div class="info_utente">
						<h2><%= @user.fullname %></h2>
						<%
							#TODO calcolare veramente gli anni dell'utente
						%>
						<p>23 anni, <%= @user.city %></p>
					</div>
					<div class="riepilogo">
						<span class="btn btn-info disabled">
							<span><%= @number_events_created %></span>
							<br /><%
							if @events.length!=1
								%>EVENTI CREATI<%
							else
								%>EVENTO CREATO<%
							end%></span>
						<span class="btn btn-info disabled">
							<span><%= @participated_events.length %></span>
							<br /><%
							if @events.length!=1
								%>EVENTI VISSUTI<%
							else
								%>EVENTO VISSUTO<%
							end%></span>
						<span class="btn btn-info disabled">
							<span><%= @comments.length%></span>
							<br />
							COMMENTI
						</span>
					</div>
			</div>
		</div>
		<div class="row visible-phone">
			<%= render 'users/profile_pic_logged', user: @user, size: "medium"%>
			<div class="info_utente">
				<h2><%= @user.fullname %></h2>
				<p>23 anni, <%= @user.city %></p>
				<%=render partial: 'users/controls', user: @user %>
			</div>
			<div class="riepilogo">
				<span class="btn btn-info disabled">
					<span><%= @number_events_created %></span>
					<br /><%
					if @events.length!=1
						%>EVENTI CREATI<%
					else
						%>EVENTO CREATO<%
					end%></span>
				<span class="btn btn-info disabled">
					<span><%= @participated_events.length %></span>
					<br /><%
					if @events.length!=1
						%>EVENTI VISSUTI<%
					else
						%>EVENTO VISSUTO<%
					end%></span>
				<span class="btn btn-info disabled">
					<span><%= @comments.length %></span>
					<br />
					COMMENTI
				</span>
			</div>
		</div>
		<section class="commenti_recenti">
			<h3>Ultimi commenti</h3>
			<a class="more">tutti..</a>
			<%= render collection: @last_comments, partial: 'comments/comment_user' %>
		</section>
		<section class="eventi">
			<h3>Eventi</h3>
			<!--contenuto della dashboard con i miei contenuti-->
			<ul id="tab_eventi_utente" class="nav nav-tabs">
				<li class="active">
					<a href="#concerti_creati" data-toggle="tab"><%= pluralize(@events.length, "Evento") %> <%if @events.length!=1%>creati<%else%>creato<%end%></a>
				</li>
				<li>
					<a href="#concerti_partecipati" data-toggle="tab"><%= pluralize(@participated_events.length, "Evento") %> vissuti</a>
				</li>
				<li>
					<a href="#concerti_futuri" data-toggle="tab"><%= pluralize(@participating_events.length, "Evento") %> futuri</a>
				</li>
			</ul>
			<div id="myTabContent" class="tab-content">
				<div class="tab-pane fade in active" id="concerti_creati">
					<div id="eventi_creati">
						<%= render @events %>
					</div>
				</div>
				<div class="tab-pane fade" id="concerti_partecipati">
					<div id="eventi_partecipazione">
						<%= render collection: @participated_events, partial: 'events/event' %>
					</div>
				</div>
				<div class="tab-pane fade" id="concerti_futuri">
					<div id="eventi_futuri">
						<%= render collection: @participating_events, partial: 'events/event' %>
					</div>
				</div>
			</div>
		</section>
	</div>
	
	<aside class="span3">
		<% if !current_user?(@user) && signed_in? %>
		<section class="hidden-phone">
			<%= render partial: 'users/controls', user: @user %>
		</section>
		<%end%>
		<section class="badges">
			<h3>Badges</h3>
			<span class="badge badge-info">6</span>
			<% 
				#STAMPO 4 BADGE PER RIGA
				n_badge = 6;
				
				#NUMERO MASSIMO DI IMMAGINI-MINIATURE PER TIPO
				max_img = 8;
				
				for i in 0..n_badge-1 do
					break if (i==max_img)
			%>
				<img src="/assets/badge.png" alt="Badge" class="badge_sniff"/>			
			<%
				end
			%>
		</section>
		<section class="elenco_immagini segue">
			<h3>Segue</h3>
			<span class="badge badge-info"><%= @followed_users.size() %></span>
			<%if (@followed_users.size == 0) then%><p>L'utente non è follower di nessuno</p><%end%>
			<% 	n_img = 0;
				if @followed_users.any? 
            		@followed_users.each do |followed_user|
               			@user = followed_user
                    	@size = "thumb" %>
                        <a href="<%= user_path(@user) %>"><%= render 'users/profile_pic', user:@user, size:@size %></a>
           	<%
           				n_img = n_img+1;
           				break if (n_img==max_img)
           			end
           		end
           	%>
		</section>
		<section class="elenco_immagini seguito">
			<h3>Seguito da</h3>
			<span class="badge badge-info"><%= @followers.size() %></span>
			<%if (@followers.size == 0) then%><p>L'utente non ha nessun follower</p><%end%>
			<%	n_img = 0;
				if @followers.any?
            		@followers.each do |seguito_da|
                		@user = seguito_da
                    	@size = "thumb" %>
                        <a href="<%= user_path(@user) %>"><%= render 'users/profile_pic', user:@user, size:@size %></a>
           	<%
           				n_img = n_img+1;
           				break if (n_img==max_img)
           			end
            	end
            	@user = @user_copy %>
		</section>
        <section class="elenco_immagini band_appartiene">
        	<h3>Nelle band</h3>
        	<span class="badge badge-info"><%= @user.bands.size() %></span>
        	<%if (@user.bands.size == 0) then%><p>L'utente non appartiene a nessuna band</p><%end%>
        	<ul>
			<% @user.bands.each do |band| %>
				<li><%= link_to band.name, band_path(band) %></li>
			<% end %>
			</ul>
        </section>
        <section class="elenco_immagini band_fan">
        	<h3>Fan delle band</h3>
        	<span class="badge badge-info"><%= @user.favourite_bands.size() %></span>
        	<%if (@user.favourite_bands.size == 0) then%><p>L'utente non è fan di nessuna band</p><%end%>
        	<ul>
			<% @user.favourite_bands.each do |band| %>
				<li><%= link_to band.name, band %></li>
			<% end %>
			</ul>
        </section>
    </aside>
</div>