config/routes.rb
SniffSound::Application.routes.draw do

  get "comments/create"

  get "comments/destroy"

  get "comment/create"

  get "comment/destroy"

  get "fan_band_relationships/create"

  get "fan_band_relationships/destroy"

  root to: 'pages#home'
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/home', to: 'pages#home'
  match '/about', to: 'pages#about'
  match '/dashboard', to: 'pages#dashboard'
  match '/explore', to: 'pages#explore'
  match '/profile', to: 'pages#profile'
  match '/search', to: 'pages#search'
  
  match '/users/search_autocompletion', to: 'users#search_autocompletion'
  
  match '/auth/:provider/callback', to: 'users#new'
  match '/auth/failure', to: 'users#failure'
  
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy] #routes per il controller di sessione (specifico quali devono essere i metodi accessibili dal controller)
  resources :bands
  resources :events do
    collection do
      get :search
    end
  end

  resources :user_event_relationships
  resources :fan_band_relationships, only:[:create, :destroy]
  resources :comments, only:[:create, :destroy]
  resources :user_user_relationships, only:[:create, :destroy]
  
  

end

app/models/band.rb
class Band < ActiveRecord::Base

  attr_accessible :description, :name
  
  has_many :event_band_relationships, dependent: :destroy
  has_many :participating_events, through: :event_band_relationships, source: :event
  has_many :band_genre_relationships, dependent: :destroy
  has_many :music_genres, through: :band_genre_relationships, source: :genre

  validates :name, presence: true,
                   uniqueness: { case_sensitive: false,
                                 message: "nome in uso" }
  has_many :user_band_relationships, dependent: :destroy
  has_many :members, through: :user_band_relationships, source: :user
  has_many :fan_band_relationships, dependent: :destroy
  has_many :fans, through: :fan_band_relationships, source: :user
 #metodi per aiutarsi a reperire dati utili
 
 def administrator_role
   self.user_band_relationships.find_by_user_id(self.administrator.id).role
 end
 
 def administrator
   User.find_by_id(self.user_band_relationships.find_by_priviledges(true).user_id)
 end
 def administrator?(user)
   self.administrator==user
 end
 #aggiornamento band
 
 def update_attributes_and_members(params)
   self.update_attributes(params[:band])
   #Eliminazione dei membri
   if not params[:delete_member].nil?
     params[:delete_member].each do |k,v|
       if not administrator?(User.find_by_id(k))
        self.user_band_relationships.find_by_user_id(k).destroy
       end
     end
   end
   #Ruolo dei membri
   self.user_band_relationships.find_by_user_id(self.administrator.id).update_attributes(role:params[:role])#amministratore
   if not params[:member_role].nil?
     params[:member_role].each do |k,v| #altri utenti
       if !self.user_band_relationships.find_by_user_id(k).nil? && v!=self.user_band_relationships.find_by_user_id(k).role
         self.user_band_relationships.find_by_user_id(k).update_attributes(role:v)
       end
     end
   end
   #Generi
   if not params[:genre].nil?
     if not self.band_genre_relationships.nil? #Tolgo le relazioni coi generi precedenti
       self.band_genre_relationships.all.each do |relationship|
         relationship.destroy
       end
     end
     params[:genre].each do |k,v|
       if (Integer(v) == 1)
         self.band_genre_relationships.create(genre_id:k)
       end
     end
   end
 end
 
 #controllo che i membri aggiunti siano corretti
 def build_members(params,current_user_id)
   if not params[:member].nil?
      params[:member].each do |k,v|
        if((!User.find_by_id(v[:id]).nil?) && User.find_by_id(v[:id]).fullname==v[:name] && Integer(current_user_id)!=Integer(v[:id]))
          Rails.logger.info("#{current_user_id} uguale a #{v[:id]}")
         self.user_band_relationships.find_or_initialize_by_user_id(user_id: v[:id], role: v[:role])  
        end
      end
    end
 end
  
 #metodi di ricerca delle band---------------------------------------------------------------------------------------------------------- 
  def self.search(params)
    if params
       where('name ILIKE ?', "%#{params[:search]}%") 
    else
      scoped
    end
  end   
  
  #metodo per aggiungere i generi
  def music_genre(params)
    if not params[:genre].nil?
      params[:genre].each do |k,v|
          self.band_genre_relationships.create(genre_id:Genre.find(k).id)
      end  
    end
  end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_filter :signed_in_user, only: [:new,:create]
  
  
  def new
    @band = Band.new
    @users = User.all.to_json(only:[:id,:fullname]).to_s.html_safe;
  end
  
  def create
    @band = Band.new(params[:band])
    @band.user_band_relationships.build(user_id:current_user.id,priviledges:1,role:params[:role])
    @band.build_members(params,current_user.id)
    if @band.save
      @band.music_genre(params)
      flash[:success] = "Band creata correttamente!"
      redirect_to band_path(@band)
    else
      render 'new'
    end
  end  
  
  def edit
    @band = Band.find(params[:id])
    users = User.all
    @clean_users = users.to_json(only:[:id,:fullname]).to_s.html_safe
  end
  
  def update
    @band = Band.find(params[:id])
    @band.build_members(params,current_user.id)
    @band.update_attributes_and_members(params)
    redirect_to band_path(@band)
  end
  
  def show
    @band = Band.find(params[:id])
    @band_events = @band.participating_events
    @band_future_events = @band_events.search_all_future
    @band_past_events = @band_events.search_all_past
    @band_live_events = @band_events.search_events_live
    @total_audience = @band_events.count(group: :user).length
  end
  
  def destroy
    band = Band.find(params[:id])
    url = request.referer
    if("#{request.referer}/edit".include?(edit_band_path(band)))
      url = root_path
    end
    
    band.destroy
    
    redirect_to url
  end 
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/views/bands/_controls_edit.html.erb
<% if current_user?(@band.administrator)%>
<section class="admin_controls">
	<h3>Amministratore</h3>
	<%= link_to "Modifica band", edit_band_path(@band), class:"btn btn-inverse" %>
	<%= link_to "Elimina band", band_path(@band), class:"btn btn-danger", method: :delete, confirm: "Sei sicuro di voler cancellare la band ?" %>
	<%
		#TODO bisognerebbe reindirizzare la pagina!
	%>
</section>
<% end %>

app/views/bands/_controls_fan.html.erb
<% if !current_user?(@band.administrator) && signed_in? %>
<div class="band_controls_fan" id = "band_controls<%= @band.id %>">
	<% if not current_user.fan?(@band) 
		%><%= render 'bands/fan', band:@band %><% 
			else
				%><%= render 'bands/unfan', band:@band %><%
			end
	%>
</div>
<% end %>

app/views/bands/_fan.html.erb
<%= link_to "Diventa Fan", fan_band_relationships_path(band_id:@band.id, user_id:current_user.id), id: "diventa_fan_#{@band.id}", class:"btn btn-small btn-info", remote: true, method: :post %>

app/views/bands/_unfan.html.erb
<% @relationship = @band.fan_band_relationships.find_by_user_id(current_user.id) %>
<%= link_to "Non sono più fan", fan_band_relationship_path(id:@relationship.id), remote: true, id: "diventa_fan_#{@band.id}", class:"btn btn-small btn-warning", method: :delete %>

app/views/bands/edit.html.erb
<% provide(:title, 'Modifica: '+@band.name) %>
<div class="row">
	<div class="span8 offset2">
		<h1>Modifica <%= @band.name %></h1>
		<%= form_for(@band) do |f| %>
			<%= render 'shared/error_messages', object: f.object %> <!-- visualizza i messaggi di errore -->
			<ol>
				<li>Nome e descrizione della band</li><hr>
				<%= f.text_field :name, placeholder:"Nome della band" %>
				<%= render 'shared/error_messages_for', object: f.object, field: :name %>
				
				<%= f.text_area :description, placeholder:"Descrizione", cols: 30, rows: 5 %>
				<%= render 'shared/error_messages_for', object: f.object, field: :description %>
				
				<li>Il tuo ruolo nella band</li><hr>
				<%= text_field_tag "role", @band.administrator_role, placeholder: "Amministratore" %>
				<li>Modifica i membri della band:</li>
				<ul>
					<% @band.members.each do |member| %>
						<% if not member.id == @band.administrator.id %>
							<li>Elimina: <%= check_box_tag "delete_member[#{member.id}]"%> <%= member.fullname %> <%= text_field_tag "member_role[#{member.id}]", @band.user_band_relationships.find_by_user_id(member.id).role %></li>
						<% end %>
					<% end %>
				</ul>
				<%
					#TODO meglio il layout dei punti elenco dei membri della band
				%>
				<li>Componenti della band<a href="#" class="aggiungi_membro">[aggiungi un nuovo membro]</a></li>	<hr>
				<%= text_field_tag "member[0][name]", nil, placeholder: "Cerca tra gli utenti..", class:"user_autocompletion", data: {provide: "typeahead"}, autocomplete: 'off' %>
				<%= hidden_field_tag "member[0][id]" %>
				<%= text_field_tag "member[0][role]", nil, placeholder: "Es. cantante, chitarrista...", class:"user_role" %>
				<a href="#" class="togli_membro btn btn-danger" id="togli_membro_0">Remove</a>
				
				<li>Genere:</li><hr>
				<% Genre.all.each do |genre| %>
					<% checkit = @band.music_genres.find_by_id(genre.id).nil? %>
					<div class="checkbox_container">
						<%= check_box_tag "genre[#{genre.id}]", 1, !@band.music_genres.find_by_id(genre.id).nil? %>
						<%= label_tag "genre[#{genre.id}]", genre.name %>
					</div>
				<% end %>
			</ol>

			<%= f.submit "Modifica Band", class:"btn btn-large btn-primary" %>		
		<% end %>
	</div>
<script type="text/javascript">
	var all_users = <%= @clean_users %>; //mi faccio dare dal controller tutti gli utenti
	$('.edit_band').submit(function() {
		if ($(this).valid())
			$("input[type='submit']").button("loading");
		return true;
	});
</script>
<%= javascript_include_tag "page-specific/band_member_selection" %>
	
</div>

app/views/bands/new.html.erb
<% provide(:title, 'Registra Band') %>
<div class="row">
	<div class="span8 offset2">
		<h1>Aggiungi la tua band (di cui sarai amministratore)</h1>
		<%= form_for(@band) do |f| %>
			<%= render 'shared/error_messages', object: f.object %> <!-- visualizza i messaggi di errore -->
			<ol>
				<li>Nome e descrizione della band</li><hr>
				
				<%= f.text_field :name, placeholder:"Nome della band" %>
				<%= render 'shared/error_messages_for', object: f.object, field: :name %>
				
				<%= f.text_area :description, placeholder:"Descrizione", cols: 30, rows: 5 %>
				<%= render 'shared/error_messages_for', object: f.object, field: :description %>
				
				<li>Il tuo ruolo nella band</li><hr>
				<%= text_field_tag "role", nil, placeholder: "Es. cantante, chitarrista..." %>
				
				<li>Componenti della band<a href="#" class="aggiungi_membro">[aggiungi un nuovo membro]</a></li>	<hr>
				<%= text_field_tag "member[0][name]", nil, placeholder: "Cerca tra gli utenti..", class:"user_autocompletion", data: {provide: "typeahead"}, autocomplete: 'off' %>
				<%= hidden_field_tag "member[0][id]" %>
				<%= text_field_tag "member[0][role]", nil, placeholder: "Es. cantante, chitarrista...", class:"user_role" %>
				<a href="#" class="togli_membro btn btn-danger" id="togli_membro_0">Remove</a>
				
				<li>Genere:</li><hr>
				<% Genre.all.each do |genre| %>
					<div class="checkbox_container">
						<%= check_box_tag "genre[#{genre.id}]"%>
						<%= label_tag "genre[#{genre.id}]", genre.name %>
					</div>
				<% end %>
			</ol>

			<%= f.submit "Crea la tua band", class:"btn btn-large btn-primary" %>		
		<% end %>
	</div>
	
<script type="text/javascript">
	var all_users = <%= @users %>; //mi faccio dare dal controller tutti gli utenti
	$('#new_band').submit(function() {
		if ($(this).valid())
			$("input[type='submit']").button("loading");
		return true;
	});
</script>
<%= javascript_include_tag "page-specific/band_member_selection" %>
	
</div>

app/views/bands/show.html.erb
<% provide(:title, @band.name) %>

<%
	#TODO comportamento dinamico quando divento fan o mi tolgo
	#TODO sistemare il layout in base alla lunghezza del nome utente e/o del nome della band
%>

<%= javascript_include_tag "page-specific/regola_altezza_aside" %>

<div class="row">
	
	<!--PARTE SINISTRA-->
	<div class="span7 offset1">
		<!-- versione desktop -->
		<div class="row hidden-phone" id="row_band">
			<div class="span2" id="foto_band">
				<%
					#TODO immagine associata alla band !
				%>
				<% @user = current_user%>
				<%= render 'users/profile_pic_logged', user: @user, size: "medium"%>
			</div>
			<div class="span5" id="descr_band">
				<div class="info_band">
					<h2><%= @band.name %></h2>
					<%
						#TODO spostare questo codice nel controller
						@str = ""
						i = 1;
						if (@band.music_genres.any?)
							@band.music_genres.each do |b|	
								@str = @str + b.name
								if (i<@band.music_genres.count)
									if (i==@band.music_genres.count-1)
										@str = @str + " e "
									else
										@str = @str + ", "
									end
								end
								i=i+1
							end
						end		
					%>
					<p><%= @str.html_safe %></p>
				</div>
				<div class="riepilogo">
					<span class="btn btn-success disabled">
						<span><%= @band_events.count %></span>
						<br /><%
						if @band_events.length!=1
							%>EVENTI<%
						else
							%>EVENTO<%
						end%></span>
					<span class="btn btn-success disabled">
						<span><%= @band.fans.count %></span>
						<br />FAN</span>
					<span class="btn btn-success disabled">
						<span><%= @total_audience %></span>
						<br />SPETTATORI</span>
				</div>
			</div>
		</div>
		<div class="row visible-phone">
			<%
				#TODO immagine associata alla band !
			%>
			<% @user = current_user%>
			<%= render 'users/profile_pic_logged', user: @user, size: "medium"%>
			<div class="info_band">
				<h2><%= @band.name %></h2>
				<p><%= @str.html_safe %></p>
				<%= render partial: 'bands/controls_fan', band: @band %>
			</div>
			<div class="riepilogo">
				<span class="btn btn-success disabled">
					<span><%= @band_events.count %></span>
					<br /><%
					if @band_events.length!=1
						%>EVENTI<%
					else
						%>EVENTO<%
					end%></span>
				<span class="btn btn-success disabled">
					<span><%= @band.fans.count %></span>
					<br />FAN</span>
				<span class="btn btn-success disabled">
					<span><%= @total_audience %></span>
					<br />SPETTATORI</span>
			</div>
		</div>
		<section id="bio_band">
			<h3>Biografia</h3>
			<p><%= @band.description%></p>
		</section>
		<section class="eventi">
			<h3>Eventi</h3>
			<ul id="tab_eventi_band" class="nav nav-tabs">
				<li class="active">
					<a href="#concerti_live" data-toggle="tab"><%= pluralize(@band_live_events.length, "Evento") %> live</a>
				</li>
				<li>
					<a href="#concerti_passati" data-toggle="tab"><%= pluralize(@band_past_events.length, "Evento") %> passati</a>
				</li>
				<li>
					<a href="#concerti_futuri" data-toggle="tab"><%= pluralize(@band_future_events.length, "Evento") %> futuri</a>
				</li>
			</ul>
			<div id="myTabContent" class="tab-content">
				<div class="tab-pane fade in active" id="concerti_live">
					<div id="eventi_creati">
						<%= render collection: @band_live_events, partial: 'events/event' %>
					</div>
				</div>
				<div class="tab-pane fade" id="concerti_passati">
					<div id="eventi_partecipazione">
						<%= render collection: @band_past_events, partial: 'events/event' %>
					</div>
				</div>
				<div class="tab-pane fade" id="concerti_futuri">
					<div id="eventi_futuri">
						<%= render collection: @band_future_events, partial: 'events/event' %>
					</div>
				</div>
			</div>
		</section>
	</div>
	
	<!--PARTE DESTRA-->
	<aside class="span3">
		<% if !current_user?(@band.administrator) && signed_in? %>
		<section class="hidden-phone">
			<%= render partial: 'bands/controls_fan', band: @band %>
		</section>
		<% end %>
		<section class="membri">
			<h3>Membri</h3>
			<span class="badge badge-success"><%=@band.members.count%></span>
			<% @band.members.all.each do |member|
				@membro =  @band.user_band_relationships.find_by_user_id(member.id)
				@user=member%>
				<article>
					<%
						#TODO far funzionare il partial delle immagini.. il link è giusto ma l'immagine è sempre quella del current_user
					%>
					<a href="<%= user_path(member) %>"><%= render 'users/profile_pic', user:member, size:@size %></a>
					<p class="nome_membro"><b><%= link_to member.fullname, user_path(member) %></b></p>
					<p class="ruolo_membro"><%= @membro.role %></p>
				</article>
			<% end %>
		</section>
		<section class="elenco_immagini fan">
			<h3>Fan</h3>
			<span class="badge badge-success"><%= @band.fans.size %></span>
			<%
			max_img = 8;
			
			if (@band.fans.size == 0) then
				%><p>La band non ha nessun fan</p><%
			end
			
			n_img = 0;
			if @band.fans.any? 
           		@band.fans.each do |fan|
           			@user = fan
                  	@size = "thumb" %>
                        <a href="<%= user_path(@user) %>"><%= render 'users/profile_pic', user:@user, size:@size %></a>
           	<%
           				n_img = n_img+1;
           				break if (n_img==max_img)
           			end
           		end
           	%>
		</section>
		<%= render partial: 'bands/controls_edit', band: @band %>
	</div>
	
</div>