config/routes.rb
SniffSound::Application.routes.draw do

  get "comments/create"

  get "comments/destroy"

  get "comment/create"

  get "comment/destroy"

  get "fan_band_relationships/create"

  get "fan_band_relationships/destroy"

  root to: 'pages#home'
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/home', to: 'pages#home'
  match '/about', to: 'pages#about'
  match '/dashboard', to: 'pages#dashboard'
  match '/explore', to: 'pages#explore'
  match '/profile', to: 'pages#profile'
  match '/search', to: 'pages#search'
  
  match '/users/search_autocompletion', to: 'users#search_autocompletion'
  
  match '/auth/:provider/callback', to: 'users#new'
  match '/auth/failure', to: 'users#failure'
  
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy] #routes per il controller di sessione (specifico quali devono essere i metodi accessibili dal controller)
  resources :bands
  resources :events do
    collection do
      get :search
    end
  end

  resources :user_event_relationships
  resources :fan_band_relationships, only:[:create, :destroy]
  resources :comments, only:[:create, :destroy]
  resources :user_user_relationships, only:[:create, :destroy]
  
  

end

app/views/layouts/_footer.html.erb
<hr>
<footer id="page_footer">

  <nav class="row">
    <ul>
      	<li class="span2">
		  	<a href="https://bitbucket.org/luigidr/lam2012"><span class="label label-inverse">Repository</span></a>
  		</li>

		<li class="span1 offset7"><a href="http://bit.ly/lingambmult">News</a></li>
      
      	<li class="span1"><%= link_to "About", about_path %></li>
    </ul>
  </nav>
  
</footer>

app/views/layouts/_header.html.erb
<!-- Navigation bar -->
<header class="navbar navbar-fixed-top">
  	<div class="navbar-inner">
  	  	<div class="container">
  	    	
  	    	<!-- .btn-navbar is used as the toggle for collapsed navbar content -->
		    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		    </a>
		    
		    <a class="brand" href="<%=root_path%>">SniffSound</a>
			
			<div class="nav-collapse">
	  	    <% if !signed_in? %>
	  	    	<ul class="nav pull-right">
			  		<li><%= link_to "Aiuto", "#" %></li>
			  		<li class="divider-vertical"></li>
			  		<li><a href="#" onclick="$('#homeCarousel').carousel(4);">Registrati</a></li>
       				<li class="divider-vertical"></li>
			  		<li><a data-toggle="modal" href="#loginModale">Accedi</a></li>
	        	</ul>
	        <% else %>
	        	<ul class="nav pull-right">
		        	<li><%= form_tag search_path, method: 'get', class: 'navbar-search pull-left' do %>
								<%= text_field_tag :search, params[:search], class: 'search-query span2', placeholder:'cerca qualcosa..' %>
						<% end %>
					</li>
					<li class="divider-vertical"></li>
		        	<li><%= link_to "Crea Evento", new_event_path %></li>
		    		<li class="divider-vertical"></li>
		    		<li><%= link_to "Registra Band", new_band_path %></li>
		    		<li class="divider-vertical"></li>
				  	<li><%= link_to "Eventi", explore_path %></li>
		    		<li class="divider-vertical"></li>
				  	<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
	          				<%=@current_user.fullname%>
	          				<b class="caret"></b>
	    				</a>
						<ul class="dropdown-menu">
							<li><%= link_to "Profilo Pubblico", user_path(current_user) %></li>
							<li><%= link_to "Dati Personali", edit_user_path(current_user) %></li>
							<li><%= link_to "Esci", signout_path, method: "delete" %></li>
						</ul>
					</li>
	        	</ul>
	        <% end %>
	        </div>
		</div>
	</div>
</header>

<% if !signed_in? %>
<!-- Solo se l'utente non è loggato.. -->
<%= render 'sessions/new' %>
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= full_title(yield(:title)) %></title>
		<link rel="SHORTCUT ICON" href="assets/favourite.png"/>
		<!-- The following Rails functions tell the application to use application.css (that automatically includes the CSS files created with the controllers)
		  	as stylesheet and application.js as javascript resource -->
		<%= stylesheet_link_tag "application", :media => "all" %>
		<% # the previous line is equal to stylesheet_link_tag"application", { :media => "all" }) %>
		<%= javascript_include_tag "application" %>

		<!-- The following Rails method automatically prevents Cross-Site Request Forgery (see http://en.wikipedia.org/wiki/Cross-site_request_forgery for further information) -->
		<%= csrf_meta_tags %>
		<%= render 'layouts/shim' %>

		<%= @extra_head_content %>
		  
		<!-- <link rel="SHORTCUT ICON" href="favourite.png"/> -->
		
	</head>
	<body <% if (yield(:title) == 'Bacheca') %>onload="initialize()"<% end %> >
	    <%= render 'layouts/header' %>
	    <!-- Main content -->
	    <% if (yield(:title) != 'Esplora') %><div class="container"><% end %>
			<%= yield %>
			<%= if (yield(:title) != 'Esplora')
					render 'layouts/footer'
				end
			%>
	    <% if (yield(:title) != 'Esplora') %></div><% end %>
	    
<!-- 	    <%= debug(params) if Rails.env.development? %> -->	    
	</body>
</html>